// <auto-generated />
using System;
using BTL_WEBDEV2025.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTL_WEBDEV2025.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251029103130_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTL_WEBDEV2025.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpecialDeal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Men",
                            Description = "Premium running shoes with Air Max technology",
                            ImageUrl = "https://via.placeholder.com/300",
                            IsFeatured = true,
                            IsSpecialDeal = false,
                            Name = "Air Max 270",
                            Price = 150m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Unisex",
                            Description = "Classic lifestyle shoes",
                            DiscountPrice = 70m,
                            ImageUrl = "https://via.placeholder.com/300",
                            IsFeatured = true,
                            IsSpecialDeal = true,
                            Name = "Air Force 1",
                            Price = 90m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Men",
                            Description = "High-performance running shoes",
                            ImageUrl = "https://via.placeholder.com/300",
                            IsFeatured = true,
                            IsSpecialDeal = false,
                            Name = "Zoom Pegasus",
                            Price = 120m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Women",
                            Description = "Everyday running for women",
                            ImageUrl = "https://via.placeholder.com/300",
                            IsFeatured = true,
                            IsSpecialDeal = false,
                            Name = "Revolution 6",
                            Price = 60m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Men",
                            Description = "Basketball lifestyle shoes",
                            DiscountPrice = 45m,
                            ImageUrl = "https://via.placeholder.com/300",
                            IsFeatured = false,
                            IsSpecialDeal = true,
                            Name = "Court Vision",
                            Price = 65m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Unisex",
                            Description = "Futuristic design sneakers",
                            ImageUrl = "https://via.placeholder.com/300",
                            IsFeatured = true,
                            IsSpecialDeal = false,
                            Name = "React Element",
                            Price = 130m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Women",
                            Description = "Natural motion running shoes",
                            DiscountPrice = 60m,
                            ImageUrl = "https://via.placeholder.com/300",
                            IsFeatured = false,
                            IsSpecialDeal = true,
                            Name = "Free RN",
                            Price = 80m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Unisex",
                            Description = "Skateboarding classic",
                            ImageUrl = "https://via.placeholder.com/300",
                            IsFeatured = true,
                            IsSpecialDeal = false,
                            Name = "Dunk Low",
                            Price = 100m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
